server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 5000

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp 

  datasource:
    url: jdbc:mysql://${RDS.HOSTNAME}:${RDS.PORT}/${RDS.DB.NAME}?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS.USERNAME}
    password: ${RDS.PASSWORD}

  data:
    mongodb:
      uri: mongodb://${MONGO.USERNAME}:${MONGO.PASSWORD}@${EC2.HOSTNAME}:${EC2.PORT}/${MONGO.DB.NAME}?authSource=admin

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  output:
    ansi:
      enabled: always

# S3 설정
cloud:
  aws:
    region:
      static: ${STATIC}
      auto: false
    s3:
      bucket: ${BUCKET}
    credentials:
      access-key: ${S3.AWS.ACCESS.KEY}
      secret-key: ${S3.AWS.SECRET.KEY}
    stack:
      auto: false

# Sentry 설정
sentry:
  dsn: ${SENTRY.DSN}
  enable-tracing: true
  send-default-pii: true
  environment: development
  logging:
    minimum-event-level: "WARN"
    minimum-breadcrumb-level: "INFO" 
  sample-rate: 1 

name: ${MY.JWT}
bucket: ${BUCKET}
static: ${STATIC}